/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.12                          *
*        Compiled Jun 29 2011, 15:28:47                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", 0, 0, 0, 480, 272, 0, 0x0 },
	{ PROGBAR_CreateIndirect, "Progbar", GUI_ID_PROGBAR0, 60, 200, 360, 20, 0 ,0},
	{ TEXT_CreateIndirect, "TOPRIE", GUI_ID_TEXT0, 0, 0, 480, 272, 0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

static void _cbDialog(WM_MESSAGE * pMsg) {
	int NCode;
	int Id;
	WM_HWIN hItem;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case WM_INIT_DIALOG:
			// Initialization of 'EDIT'
			// USER END
			break;
		case GUI_ID_BUTTON0: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0), "dd");
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
void Login_SetProgbar(WM_HWIN hWin, char Value)
{
	WM_HWIN hItem;
	hItem = WM_GetDialogItem(hWin, GUI_ID_PROGBAR0);
	PROGBAR_SetValue(hItem, Value);
	GUI_Exec();
}

WM_HWIN CreateLogin(void);
WM_HWIN CreateLogin(void) {
	char i;
	WM_HWIN hWin,hItem;
	hWin =GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
	WINDOW_SetBkColor(hWin, GUI_BLUE);
	hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT0);
	TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
	TEXT_SetTextColor(hItem, GUI_WHITE);
	TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
	for (i = 0;i < 101;i++)
	{
		Login_SetProgbar(hWin, i);
		GUI_Delay(10);
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
